### ISSUE TITLE
Recently created Events are not displaying - Home page seems to have reverted

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#124]
I'm seeing the 'old' seed data on the home page, but not the more recently created events (Sequoia Grove) since we talked today. 
Let's not display the Hillary and Bernie seed data for this deployment.
![capture d ecran 2016-05-15 a 7 07 33 pm](https://cloud.githubusercontent.com/assets/12802756/15278668/a11fcd30-1ad0-11e6-999b-a7d830ca82f3.png)

**Comment by virajmahesh** [comment]
Sorry about that. I had to wipe the entire database in order to get rid of the old skills.

I can get rid of the test events for this deployment, but do you think that it might be better to just remove them permanently? I feel like they might have outlived their utility since you always create your own events while testing, but let me know if you feel that they might come in handy later.

**Comment by mplauche** [comment]
I agree. we are done with those.

**Comment by virajmahesh** [comment]
I have manually deleted the two test events that were created.
I also removed the automatic creation of the test events. I noticed that you've created a few events, so I don't want to wipe the database, but the next time we do a wipe, the events won't show up.

**Comment by mplauche** [comment]
thanks. good call - I want to show this content to one more person before we wipe it. I'll let you know when she has had a chance to check it out.
