### ISSUE TITLE
New Notifications Hyperlinks are purple - signaling that they have been viewed.

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#169]
this just happened when you were working on SKILLS display
![capture d ecran 2016-05-21 a 9 46 08 am](https://cloud.githubusercontent.com/assets/12802756/15449706/6f719bb0-1f3a-11e6-9c41-db478895cf2e.png)

**Comment by virajmahesh** [comment]
This is happening because you've already visited the page for these events/shifts. Hence the links are purple. I could make the links permanently blue if that would help.

**Comment by mplauche** [comment]
Are you sure? It seems like something changed very recently (after you worked on SKILLS display, but I'm not exactly sure how it worked before. 

If I look at the screenshots in issue #106, it seems they were light red when they were first posted in notifications (even if I had just created an event, meaning I had visited that event page) then if I clicked on that link in the notification feed, it would change color, so that the notifications I had clicked on had one color and the notifications I had not clicked on yet had another color (the same as the little 'delete').

**Comment by virajmahesh** [comment]
I upgraded the UI library that I use in order to get the skill and issue selection checkboxes to work. This also fixed the issue of text appearing red instead of blue (which is the conventional color for links).
I can investigate more, but I do think that it's based on the pages that you visit.

You can also experiment with this by doing:
1. Run a google search for something.
2. Instead of directly clicking on a result, copy the URL beneath the link and paste it into a new tab and load the page.
3. Go back to the search results, and the link should be purple, even though you never directly clicked the link.

**Comment by mplauche** [comment]
I didn't do this experiment, but I trust you. Thanks for looking into it.
