### ISSUE TITLE
PRIORITY - Event was created, data does not appear on homepage

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#70]
Created the following event, then clicked "Back to homepage". 

![capture d ecran 2016-04-17 a 5 58 24 pm](https://cloud.githubusercontent.com/assets/12802756/14591418/1842d98c-04c6-11e6-838c-7462fc1931ad.png)

Was directed to homepage where the Test Event did not appear.
![capture d ecran 2016-04-17 a 6 00 04 pm](https://cloud.githubusercontent.com/assets/12802756/14591424/3edc3ebc-04c6-11e6-8599-b702a571a887.png)

**Comment by mplauche** [comment]
I'm not able to reduplicate this error consistently.

**Comment by virajmahesh** [comment]
I think the issue here is that the event date is the same as today's date. As discussed, we only show future events on the home page. If you create another event for a future date, it should show up.

We currently don't show events happening "today". The idea is that if you are looking for an event to volunteer for, you probably wouldn't want someone who volunteers a few hours before the event.

If you want, we can change this behavior after discussing a better set of rules that determine what events show up on the home page.

**Comment by mplauche** [comment]
Yes, I think that's it. Thanks for clarifying (again!).
